name: yuvaprabha
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flashy_tab_bar2: ^0.0.10
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  webview_flutter: ^4.10.0
  flutter_chat_ui: ^1.6.15
  uuid: ^4.5.1
  http: ^1.2.2
  flutter_chat_types: ^3.6.2
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.6
  flutter_tts: ^4.2.1
  speech_to_text: ^7.0.0
  path_provider: ^2.1.5
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/

  fonts:
    - family: Gilroy
      fonts:
        # - asset: assets/fonts/gilroy/Gilroy-Thin.ttf
        #   weight: 100
        # - asset: assets/fonts/gilroy/Gilroy-UltraLight.ttf
        #   weight: 200
        # - asset: assets/fonts/gilroy/Gilroy-Light.ttf
        #   weight: 300
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/gilroy/Gilroy-Black.ttf
          weight: 900
